### ISSUE TITLE
Image Generator not working

### ISSUE THREAD

**Issue by AdrienBeata** [tschiemer/qualtrics-gambling#1]
Hello, I have a 405 error when trying to generate the image files on the page https://tschiemer.github.io/qualtrics-gambling/wheel/wheel.html. Do you know how I can do it?
Thanks in advance!

**Comment by tschiemer** [comment]
hi, did you fullfill the mentioned requirements?

'''
Image Generator

To generate an image set with all required images you can use the following form.

To keep the overall required number of files (and download sizes) small, it is recommended to use as few colors as possible.

Requirements for form to work: files on webserver with PHP (Extensions: Zip, Imagick)
Wether authorization for image generation is required is set at the beginning of the wheel.php file, where you also can choose your favourite username/password combination.
'''
